linha = input() .split()
pecaCODE = int(linha[0])
npeca = int(linha[1])
valorpeca = float(linha[2])
linha2 = input() .split()
pecaCODE2 = int(linha2[0])
npeca2 = int(linha2[1])
valorpeca2 = float(linha2[2])
total = (valorpeca*npeca + valorpeca2*npeca2)
print("VALOR A PAGAR: R$ %.2f" % total)
